[project]
name = "openchat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "ollama>=0.6.2",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
    "livekit-agents",
    "livekit-plugins-ai-coustics",
    
    "python-dotenv",
]

[project.scripts]
openchat = "openchat:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
